# constants
MAX_CHECKOUT_LINES = 300
LOW_ITEM_CART = 1
MEDIUM_ITEM_CART = 3
FULL_ITEM_CART = 5
RANDOM = -1
TIME_NEEDED_FOR_LOW_CART = 60
TIME_NEEDED_FOR_MEDIUM_CART = 180
TIME_NEEDED_FOR_FULL_CART = 300
ERROR = -1
UNDER_INDEX = -1
MAX_CHECKOUT_LINE_CAPACITY = 10000
CHECKOUT_LINES = 5